build:
  stage: build
  script:
    - make cppcheck
    - make build
  artifacts:
    paths:
      - build/debug/*
      - build/release/*

test:
  stage: test
  script:
    - make test
    - make memcheck
